export const ICON_PACKAGES = [
  {
    id: 'lucide',
    packageName: 'lucide-react',
    version: '1.43.0',
    licence: 'ISC',
    docs: 'https://lucide.dev/guide/react',
    source: 'https://github.com/lucide-icons/lucide',
    priorUse: 'Used: motion-library app/page.tsx',
    sizeProp: 'size',
    strokeProp: 'strokeWidth',
    weightProp: null,
    mirrorProp: null,
    labelProp: 'aria-label',
  },
  {
    id: 'phosphor',
    packageName: '@phosphor-icons/react',
    version: '2.1.10',
    licence: 'MIT',
    docs: 'https://github.com/phosphor-icons/react',
    source: 'https://github.com/phosphor-icons/react',
    priorUse: 'Not used. Evaluated in the 2026-09-08 reset prior-art sheet',
    sizeProp: 'size',
    strokeProp: null,
    weightProp: 'weight',
    mirrorProp: 'mirrored',
    labelProp: 'alt',
  },
  {
    id: 'tabler',
    packageName: '@tabler/icons-react',
    version: '3.46.0',
    licence: 'MIT',
    docs: 'https://tabler.io/icons',
    source: 'https://github.com/tabler/tabler-icons',
    priorUse: 'Not used. Evaluated in the 2026-09-08 reset prior-art sheet',
    sizeProp: 'size',
    strokeProp: 'stroke',
    weightProp: null,
    mirrorProp: null,
    labelProp: 'title',
  },
  {
    id: 'heroicons',
    packageName: '@heroicons/react',
    version: '2.2.0',
    licence: 'MIT',
    docs: 'https://heroicons.com',
    source: 'https://github.com/tailwindlabs/heroicons',
    priorUse: 'Not used. Evaluated in the 2026-09-08 reset prior-art sheet',
    sizeProp: 'width and height',
    strokeProp: null,
    weightProp: null,
    mirrorProp: null,
    labelProp: 'aria-label',
  },
] as const;

export type IconPackageId = (typeof ICON_PACKAGES)[number]['id'];
