export const PROSE_CONTRAST_PAIRS = [
  {
    foreground: '--ink',
    foregroundHex: '#212121',
    background: '--paper',
    backgroundHex: '#FFFFFF',
    role: 'Body, headings, quotes, and inline code on paper',
    bodyText: true,
  },
  {
    foreground: '--charcoal',
    foregroundHex: '#4A4A4A',
    background: '--paper',
    backgroundHex: '#FFFFFF',
    role: 'Lead, captions, and counters on paper',
    bodyText: true,
  },
  {
    foreground: '--accent-blue',
    foregroundHex: '#0035B1',
    background: '--paper',
    backgroundHex: '#FFFFFF',
    role: 'Link at rest on paper',
    bodyText: true,
  },
  {
    foreground: '--paper',
    foregroundHex: '#FFFFFF',
    background: '--accent-blue',
    backgroundHex: '#0035B1',
    role: 'Link hover and :focus-visible',
    bodyText: true,
  },
  {
    foreground: '--ink',
    foregroundHex: '#212121',
    background: '--accent-yellow',
    backgroundHex: '#DEF54F',
    role: 'Link press :active',
    bodyText: true,
  },
  {
    foreground: '--paper',
    foregroundHex: '#FFFFFF',
    background: '--ink',
    backgroundHex: '#212121',
    role: 'Code block text on ink',
    bodyText: true,
  },
  {
    foreground: '--line',
    foregroundHex: '#D9D9D9',
    background: '--paper',
    backgroundHex: '#FFFFFF',
    role: 'Horizontal rule and table hairline. Not body text.',
    bodyText: false,
  },
  {
    foreground: '--quiet',
    foregroundHex: '#A6A6A6',
    background: '--paper',
    backgroundHex: '#FFFFFF',
    role: 'Quiet token. Not used for prose text.',
    bodyText: false,
  },
] as const;
